apiVersion: apps/v1
kind: Deployment
metadata:
  name: app2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app2
  template:
    metadata:
      labels:
        app: app2
    spec:
      containers:
      - name: app2
        image: rajendrarathore/app2:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 6001
---
apiVersion: v1
kind: Service
metadata:
  name: app2
spec:
  ports:
  - port: 6001
  selector:
    app: app2
